name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run benchmarks
        run: go version && go test -bench=.
